---
steps:
  - block: ":thinking_face: What now?"
    prompt: "Choose the next set of steps to be dynamically generated"
    fields:
      - select: "Choices"
        key: "choice"
        options:
          - label: ":terminal: Show some cool log features"
            value: "logs"
          - label: ":memo: Create some annotations"
            value: "annotations"
          - label: ":people_holding_hands: Run some jobs in parallel"
            value: "parallel-steps"
          # - label: ":bird: Show an automatic retry"
          #   value: "auto-retry"
          - label: ":gift: Download an artifact"
            value: "artifact"
          - label: ":rocket: Show an annotation updating dynamically"
            value: "dynamic-annotation"
          - label: ":thumbsup: Pass the build"
            value: "pass"
          - label: ":thumbsdown: Fail the build"
            value: "fail"
  - label: ":robot_face: Process Input"
    command: ".buildkite/demokite.sh"
